# 1. Build
FROM python:3.14-alpine as builder

WORKDIR /app

COPY ./requirements.txt .

RUN apk add --no-cache --update
RUN python -m pip install --no-cache-dir --prefix=/app_libs -r requirements.txt

# 2. Run
FROM python:3.14-alpine as runner

WORKDIR /app

COPY --from=builder /app_libs /usr/local
COPY ./src src
COPY ./tests tests

EXPOSE 8000

ENTRYPOINT ["fastapi", "run", "server.py"]
CMD ["--host", "0.0.0.0", "--port", "8000"]
