FROM python:3.14-alpine

WORKDIR /app

COPY ./src/requirements.txt .
COPY ./src/server.py .

RUN apk add --no-cache --update
RUN python -m pip install -r requirements.txt

EXPOSE 8000

ENTRYPOINT ["fastapi", "run", "server.py"]
CMD ["--host", "0.0.0.0", "--port", "8000"]
